
development:
  adapter: postgresql
  encoding: unicode
  database: geolocation_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: geolocation_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: geolocation_production
  pool: 5
  username:
  password: